apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Z3Vlc3Q= # guest
  MYSQL_USER: Z3Vlc3Q= # guest
  MYSQL_PASSWORD: Z3Vlc3Q= # guest
  MYSQL_DATABASE: aW9uX3VzZXJz # ion_users
